package com.sunmi.sunmik1demo.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunmi.sunmik1demo.bean.blescan.BraceletUserBean;
import com.sunmi.sunmik1demo.bean.blescan.FilterMacBean;
import com.sunmi.sunmik1demo.bean.GvBeans;

import com.sunmi.sunmik1demo.bean.BraceletUserBeanDao;
import com.sunmi.sunmik1demo.bean.FilterMacBeanDao;
import com.sunmi.sunmik1demo.bean.GvBeansDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig braceletUserBeanDaoConfig;
    private final DaoConfig filterMacBeanDaoConfig;
    private final DaoConfig gvBeansDaoConfig;

    private final BraceletUserBeanDao braceletUserBeanDao;
    private final FilterMacBeanDao filterMacBeanDao;
    private final GvBeansDao gvBeansDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        braceletUserBeanDaoConfig = daoConfigMap.get(BraceletUserBeanDao.class).clone();
        braceletUserBeanDaoConfig.initIdentityScope(type);

        filterMacBeanDaoConfig = daoConfigMap.get(FilterMacBeanDao.class).clone();
        filterMacBeanDaoConfig.initIdentityScope(type);

        gvBeansDaoConfig = daoConfigMap.get(GvBeansDao.class).clone();
        gvBeansDaoConfig.initIdentityScope(type);

        braceletUserBeanDao = new BraceletUserBeanDao(braceletUserBeanDaoConfig, this);
        filterMacBeanDao = new FilterMacBeanDao(filterMacBeanDaoConfig, this);
        gvBeansDao = new GvBeansDao(gvBeansDaoConfig, this);

        registerDao(BraceletUserBean.class, braceletUserBeanDao);
        registerDao(FilterMacBean.class, filterMacBeanDao);
        registerDao(GvBeans.class, gvBeansDao);
    }
    
    public void clear() {
        braceletUserBeanDaoConfig.clearIdentityScope();
        filterMacBeanDaoConfig.clearIdentityScope();
        gvBeansDaoConfig.clearIdentityScope();
    }

    public BraceletUserBeanDao getBraceletUserBeanDao() {
        return braceletUserBeanDao;
    }

    public FilterMacBeanDao getFilterMacBeanDao() {
        return filterMacBeanDao;
    }

    public GvBeansDao getGvBeansDao() {
        return gvBeansDao;
    }

}
